name: casbin
description: An authorization library that supports access control models like ACL, RBAC, ABAC.
version: 0.0.1
homepage: https://casbin.org/
repository: https://github.com/casbin/dart-casbin
documentation: https://casbin.org/docs/en/overview

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  csv: ^5.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.7
